name: 18F Engineering Hiring Guide
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- vendor

permalink: pretty
highlighter: rouge
incremental: true
markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18F logo

# To expand all navigation bar entries by default, set this property to true:
expand_nav: true

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  internal: true
- text: Detailed process guide
  url: detailed-process/
  internal: true
- text: Correcting for unconscious bias
  url: unconcious-bias/
  internal: true
- text: Conducting phone screens
  url: phone-screens/
  internal: true
- text: Resume review guide
  url: resume-review/
  internal: true
  children:
    - text: Crediting plans
      url: crediting-plans/
      internal: true
- text: Technical Pre-work
  url: pre-work/
  internal: true
- text: Interviewing
  url: interviews/
  internal: true
  children:
  - text: Infosec Interview Guide
    url: infosec/
    internal: true
  - text: Core Values Interview Guide
    url: core-values/
    internal: true
  - text: Technical Interview Guide
    url: engineer/
    internal: true
  - text: DevOps/SRE Interview Guide
    url: devops/
    internal: true
  - text: Consulting Engineer Interview Guide
    url: consulting-engineer/
    internal: true
- text: Checking references
  url: checking-references/
  internal: true
- text: Training slide decks
  url: slides/
  internal: true

repos:
- name: 18F Engineering Hiring Guide
  description: Main repository
  url: https://github.com/18F/eng-hiring

google_analytics_ua: UA-48605964-19

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
- scope:
    path: ""
  values:
    layout: "guides_style_18f_default"

# Configuration for jekyll_pages_api_search plugin gem.
jekyll_pages_api_search:
  # Uncomment this to speed up site generation while developing.
  #skip_index: true

  # Each member of `index_fields` should correspond to a field generated by
  # the jekyll_pages_api. It can hold an optional `boost` member as a signal
  # to Lunr.js to weight the field more highly (default is 1).
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:
