title: 18F Engineering Hiring Guide
description: This guide covers the engineering selection process, from resume review to turning over a candidate to HR for an offer.
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- vendor

permalink: pretty
highlighter: rouge
incremental: true

author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18F logo

sass:
  style: compressed

github_info:
  organization: 18F
  repository: eng-hiring
  default_branch: master

google_analytics_ua: UA-48605964-19

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  -
    scope:
      path: ""
    values:
      layout: page

theme: uswds-jekyll

search_site_handle: eng-hiring.18f.gov
